### PR TITLE
Install packages from attributes

### PR DESCRIPTION
**Pull request by bheuvel**
Using this recipe, with the following attributes:
```ruby
          'chocolatey' => {
            'packages' => {
              'sysinternals' =>     { 'action' => 'install' },
              '7zip' =>             { 'action' => 'install' },
              'notepadplusplus' =>  { 'action' => 'install' },
              'GoogleChrome' =>     { 'action' => 'install' },
              'wireshark' =>        { 'action' => 'install', 'version' => '1.12.6' }
            }
```
will loop over the packages and install them with the options which can be provided to the resource.

### CODE REVIEW

**Comment by chasebolt** [comment]
I think this is out of scope and should be managed in each user's wrapper cookbook.

**Comment by mwrock** [comment]
Yeah. I think I agree with @chasebolt .

**Comment by bheuvel** [comment]
Well, you are free to use the code, or not :wink: 

For me the reason for creating this was that (for different (test)envrionments) I kept creating a wrapper cookbook with basically the folowing code (each time):

```ruby
%w{sysinternals 7zip notepadplusplus GoogleChrome Console2}.each do |pack|
  chocolatey pack
end
```
And that would be the only thing I would wrap around this cookbook.

On the other hand, also see a lot of people "just" using separate cookbooks, like for 7zip or notepad++ (without specific reason (not to use chocolatey))

_Perhaps_ not part of your goal for this cookbook, but removes the writing (by everyone) of separate resource(/(single)wrapper) for each and every package. I (myself :wink:) find removing/writing less code, very handy.

_If_ your objection is that you feel this cookbook should limit itself to installation and LWRP, I'm glad that for example the authors of haproxy (used yesterday for the first time) don't agree; they provide installation and LWRP, but also read an attribute collection which uses their LWRP to iterate over that collection.
Otherwise everyone would need to write a (wrapper) recipe, which would basically be the same for everyone. 
(Totally not saying this removes the need for wrapper cookbook BTW)
So haproxy cookbook allowed me to only include that cookbook, set some attributes, and already be done with it.
(Realize that functionally these are completely different cookbooks, but the ease of use COULD be the same)

So this code only requires (everyone) to specify a simple attribute for each (default installation of an) application, instead of a (everyone) writing separate (wrapper) cookbook for (possibly) each application.


But no earth-shaking feature :smile:, so feel free to use it if you like it, or close it if you don't

**Comment by mwrock** [comment]
closing this especially in light of the fact that using the resource in core chef is the way forward.

**Pull request closed without merging**
