### PR TITLE
Add track_path option

### PR DESCRIPTION
**Pull request by byrney**
An approach to: https://github.com/chocolatey/chocolatey-cookbook/issues/67

Added an attribute to the chocolatey resource to update the `ENV['PATH']` during the chef install run so that choc packages that make changes to the path can be run in the same recipe as those that depend on the path reflecting the changes.

### CODE REVIEW

**Comment by mwrock** [comment]
Chocolatey installs a file `RevreshEnv.cmd` in its bin that performs this same functionality. Its been a while since I have used it, but I'd suggest running it instead of your library code since it "ships" with chocolatey then see if you get the same results.

Also, we might consider just making this the default behavior rather than triggering it with a new attribute. The downside is potentially breaking people (more like a show stopper than a "down side"). When an installer adjusts your path, it seems like the right thing to do is to honor that path immediately. You see any issues there?

**Comment by byrney** [comment]
@mwrock - I wasn't aware of that, it's this script here?  https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/redirects/RefreshEnv.cmd

I agree that refreshing (or maybe merging) all the env vars, not just the path, seems like a useful thing to do. Most java stuff won't work if the `JAVA_HOME` env var is not set, for example.

Looking at the script though, I can't see how I could leverage it. It would need to run in a `cmd.exe` spawned by the chef run. The changes would be applied in the cmd subprocess rather than modifying the chef process `ENV` itself -- the next choco.exe that gets launched would not inherit the changes. Did you have another approach?

Personally, I think making this the default behaviour would be good. I tried to consider changes to `ENV['PATH']` (via ruby blocks in cookbooks) and to both the USER and MACHINE paths and merge them in a way that would not drop anything. But... it does not always preserve the ordering and so could be a breaking change. I figured to default it `false` now and then flip to `true` on a major version change so that people with  "~> 1.5" would not get a nasty surprise. 

If people are comfortable with merging this in, I'm happy to take direction on using RefreshEnv and applying it to environment variables more generally.

Thanks, 

Rob

**Comment by mwrock** [comment]
Yeah you are right. Heh I don't know what I was thinking - it has to be done in Ruby. While doing a complete refresh may be the ideal, I think `PATH` is the most important and a good start.

Do you mind just making this the default and removing the attribute?

I'll do some testing before merging that.

Also, this would warrant a 0.6.0 bump I think.

Thanks!

**Comment by byrney** [comment]
I checked against RefreshEnv and I think the patch does not use the right order.  The code, as is, does local + user + machine and it should do local + machine + user.

Seems bizarre to me that one would put the machine path before the per-user overrides, but that's what RefreshEnv does and it matches the windows default behaviour.

I'll fix that, flip the default behaviour and update the PR tonight.

**Comment by byrney** [comment]
@mwrock, modified as discussed.

**Comment by mwrock** [comment]
I think we should remove the attribute too.

**Comment by byrney** [comment]
That's pushed and ready to go.  

Removing the attribute means that tracking the path is always on. Anyone dependent on the previous behavior will have to modify their code or they won't be able to take the release.

I've left it to you to bump up the sem-ver appropriately.

**Pull request merged**
